### ISSUE TITLE
some pictures of LibreOffice in Japanese Environment at report-of-oss-license-analysis-using-fossology.md

### ISSUE THREAD

**Issue by fu7mu4** [OpenChain-Project/Japan-WG-General#1]
I think the report-of-oss-license-analysis-using-fossology.md is very nice document but with some pictures that contains Japanese characters.
Will you replace these pictures ?

https://github.com/OpenChain-Project/Japan-WG-General/blob/master/Report/Tool/report-of-oss-license-analysis-using-fossology.md

**Comment by hfukuchi** [comment]
Thank you for pointing an issue. I will check and ask the original author.

**Comment by hfukuchi** [comment]
The pictures have been replaced.
https://github.com/OpenChain-Project/Japan-WG-General/blob/master/Report/Tool/report-of-oss-license-analysis-using-fossology.md

**Comment by fu7mu4** [comment]
It could be good for every one.
I'll close this issue.
