### ISSUE TITLE
[License-Info-Guideline(JP)] "OSSコンプライアンス"という表記

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#21]
* OSSコンプライアンスの言葉が出てくるが、あくまでもライセンス情報を話に絞った方がいいのではないか？

**Comment by koizumistr** [comment]
確かこの指摘は「コンプライアンスはライセンス遵守だけに限られない」という文脈から出てきた疑問だったかと思います。

「コンプライアンス」という言葉を使っているところを抜き出してみたのですが

- OSSコンプライアンスを遵守するために ★
- 製品のOSSコンプライアンスが初めて遵守可能に ★
- OSSコンプライアンスに関する情報を含む必要
- コンプライアンス維持の上
- サプライチェーンにおけるライセンスへのコンプライアンス維持のために

という状況です。コンプライアンスは「（法令などの）遵守」という意味のはずなので★は重言ですね。これは見直しが必要だとして、そもそもこのガイドは「OSSライセンスのコンプライアンス」の話をしているのではないかと思うのです。一般公衆ガイドも「ライセンス遵守(License Compliance)」の一般公衆ガイドです。

**Comment by yoshi-i** [comment]
本件はClose可能
