### ISSUE TITLE
[License-Info-Guideline(JP)] 1章　”サプライチェーン上での...”　文面変更

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#23]
1章の
［サプライチェーン上で・・・の文言について、具体的な優しい文面にした方がいい］

製品がサプライチェーン上でつながる複数企業によって開発される場合には、サプライチェーンでつながっている全ての企業が正確なライセンス情報を提供することが必要になります。サプライチェーン上で1社でもライセンス情報の提供を正確に提供することができない場合には、その企業より下流にある企業全てがOSSライセンスを遵守できなくなります。サプライチェーンに関係する担当者全員がOSSについて正しく理解して作業することによって、製品のOSSコンプライアンスが初めて遵守可能になります。

**Comment by yoshi-i** [comment]
対応修正を行ったためClose希望
