### ISSUE TITLE
[License-Info-Guideline(JP)]  リーフレットに合わせて［OSS情報］という文言を利用する

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#24]
リーフレットではOSS情報という文言を使用しているので、リーフレットに合わせた方がいい

**Comment by koizumistr** [comment]
冒頭では「OSS情報」とありますが、それ以外にも以下のような言い方をしています。

- OSSに関する情報
- OSSに伴い提供すべき情報

**Comment by yoshi-i** [comment]
会合では、「ＯＳＳの配布に伴い提供すべき情報」とすべき、との議論があった。

**Comment by yoshi-i** [comment]
頭書きに注記の形で記載追加を行ったため、Close希望
