### ISSUE TITLE
[License-Info-Guideline(JP)]  SPDX Liteの章の冒頭でツールの存在を明示

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#26]
SPDX Liteの章でいきなりツールの話が出ているが、事前にツールを使用して自動生成出来る話を説明した方がいい

**Comment by yoshi-i** [comment]
ＳＷ３６０がSPDX Liteを読み込めるか、確認した方が良い。
ToolingのSWGとも連携して確認したい。

**Comment by yoshi-i** [comment]
SW360の件は、注記課題として要監視、別issueで管理。
文面上、SPDXの節で、ツールによる自動生成、SPDX Liteの節でツールによる自動生成ではカバーできない事項を記載する形で、本指摘に対応。
Close希望。
