### ISSUE TITLE
[License-Info-Guideline(JP)] SPDXとSPDX Liteの位置づけの章で、タグの説明が無い

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#27]
SPDXとSPDX Liteの位置づけの章で、タグの説明が無いので、説明を入れた方がいい

**Comment by yoshi-i** [comment]
「SPDXとSPDX Liteの位置づけ」に「必要な項目（タグ）」と修正を実施。
さらに、表組のなかに、License Info (Tag.)と記載。
Close希望
