### ISSUE TITLE
[License-Info-Guideline(JP)] 　Full SpecのSPDXよりもSPDX Liteによる記載の方が...　部分の表記

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#29]
Full SpecのSPDXよりもSPDX Liteによる記載の方が・・・、については、SPDX Liteの方がいいとは言えない

**Comment by yoshi-i** [comment]
「SPDXでもSPDX Liteでも、ビジネス当事者の議論で決めればよい、と言えます。」と記載
Close希望
