### ISSUE TITLE
[License-Info-Guideline(JP)] ソフトウエアとOSSの使い分け

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#31]
用語でソフトウェアが使われているが、OSSに統一した方がいいのでは？
プロプラも扱う場合もあるので、ソフトウェアの説明を入れるのはどうか？

**Comment by yoshi-i** [comment]
本家SPDXの「open source and other software packages」という記載を、頭書きで踏襲した方が良さそう

**Comment by yoshi-i** [comment]
ガイドラインとしての位置づけを、検討し、SPDX Lite導入者へのガイドとの位置づけを明確にしたい。文書名を変更。ファイル名の変更について、後日対応。
なお、サプライチェーンにおけるライセンス情報全般のガイドを試作した物は、Pull Req未発行の未完成品が、とりあえず、ある。

**Comment by yoshi-i** [comment]
文書タイトルを変更しました
Pull Reqは出せていませんが、Slackに修正版を貼りましたので、Closeします。
