### ISSUE TITLE
[License-Info-Guideline(JP)]  Files Analyzedの手作業でfalseの記載

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#32]
Files Analyzedの手作業でfalseの記載について、説明を追加した方がいい

**Comment by yoshi-i** [comment]
（なぜ"false"を記載するのか説明要、手書きだからソースコード全体をスキャンしたとは言えないため”false”になると記載すべき）と継続記載中。

**Comment by yoshi-i** [comment]
Pull Req発行後、Close

**Comment by yoshi-i** [comment]
Pull Reqは出せていませんが、Slackに修正版を貼りましたので、Closeします。
