### ISSUE TITLE
[License-Info-Guideline(JP) ]Concluded LicenseとDeclared License の説明

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#33]
Concluded LicenseとDeclared Licenseがほぼ同じ説明になっている

**Comment by koizumistr** [comment]
最初の1文以外はまったく同じ。辞書的に使うことを想定しているのならこれもあり。

原文を参照すると、concludeの方はほぼ原文に忠実だが、declaredの方はまったく異なる。

**Comment by yoshi-i** [comment]
記載修正を実施。Close希望
