### ISSUE TITLE
[License-Info-Guideline(JP)]  License Identifier 一意になる識別子の「一意」について

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#36]
License Identifier 一意になる識別子・・・とは、何の一意なのか説明が入れた方がいい

**Comment by koizumistr** [comment]
SPDXの仕様書には"Provide a locally unique identifier..."とあります。SPDX Liteファイル内にLicense Identifierを書かないといけないOSSが複数あった場合、区別がつけば十分なのではないでしょうか。

**Comment by yoshi-i** [comment]
記載お願い先: 小泉さん　(2019/10/15現在)

**Comment by koizumistr** [comment]
＜独り言＞
そもそも License-Info-Exchange/SPDX-Lite-sample/spreadsheet_sample2/SPDX-Lite-sample_20190920.xlsx みたいな形式を前提とするなら、この項目自体が冗長なのでは。

行という形で確実に特定される訳だから、、、、
＜/独り言＞

**Comment by koizumistr** [comment]
（私案）
L2.2　Package SPDX Identifier

ソフトウェア パッケージの識別子です。SPDX Liteファイルの中で一意になるように決めてください。それ以外は提供する側で自由に決めて構いません。本項目はソフトウェア パッケージの名称などだけでは区別できないパッケージを区別するために利用します。
SPDX Liteファイルを結合したりツールに取り込んだりしたりする場合に一意であることを保証するのは受領側の責任です。

L3.1　License Identifier

SPDX License Listに掲載されていないライセンスの場合、識別子を記載します。SPDX Liteファイルの中で一意になるように決めてください。それ以外は提供する側で自由に決めて構いません。 本項目は使用しているソフトウェアのライセンスを特定するために利用します。 
SPDX Liteファイルを結合したりツールに取り込んだりしたりする場合に一意であることを保証するのは受領側の責任です。

**Comment by koizumistr** [comment]
Package SPDX Identifierにも「一意」とありましたので、その辺りも含めて加筆修正してみました。

**Comment by koizumistr** [comment]
[覚書] #50 がマージされていますので、完了ということになるかと。

**Comment by yoshi-i** [comment]
L1.3記載の場合に、L2.2の記載を参考とすることとしますが、本件としては、Closeお願いします。

**Comment by yoshi-i** [comment]
クローズします
