### ISSUE TITLE
[License-Info-Guideline(JP)]    Package Comment以下の説明

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#37]
Package Comment以下の説明が無い     →    説明の順番が入れ替わっている

**Comment by yoshi-i** [comment]
本件記載について、Issueを分割した。

**Comment by yoshi-i** [comment]
対応致しました。
Pull Reqは出せていませんが、Slackに修正版を貼りましたので、Closeします。
