### ISSUE TITLE
[License-Info-Guideline(JP)] modification record以下がPackage Comment配下に入ることを説明

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#38]
modification record以下がPackage Comment配下に入る事が分かりづらい

**Comment by yoshi-i** [comment]
ソフトウェア　パッケージに関する、追加情報を記載します。 SPDX Liteでは、このタグに、以下のような情報が収められることを想定しています。

という記載を、

本項目は、SPDXの仕様上、自由記載が可能な項目であり、例えば、サプライチェーンにおけるライセンス管理に有効な、下記のようなソフトウェア　パッケージに関する、追加情報の記載を行うことが可能です。

に

**Comment by yoshi-i** [comment]
Pull Req発行後、Close予定

**Comment by yoshi-i** [comment]
対応致しました。
Pull Reqは出せていませんが、Slackに修正版を貼りましたので、Closeします。
