### ISSUE TITLE
[License-Info-Guideline(JP)]  3. ライセンス情報の収集方法 で何をいいたいのか明記

### ISSUE THREAD

**Issue by KoukiHama** [OpenChain-Project/Japan-WG-General#39]
- 3. ライセンス情報の収集方法 この章で何をいいたいのか、1～2行説明を追加する

**Comment by yoshi-i** [comment]
すべてのタグを列記すべきか、NO ASSERTIONで良いタグは、記述をスキップするか、NO ASSERTIONと書け、と明記するか、色分け含めて、要検討
本来は、SPDX Liteとして、情報を絞っているので、なるべくNO ASSERTIONに逃げては欲しくないが

**Comment by yoshi-i** [comment]
対応を実施しました。
Pull Reqは出せていませんが、Slackに修正版を貼りましたので、Closeします。
